name: Deploy Godot HTML5 to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  export-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
      
      - name: Export Godot HTML5
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          
          relative_project_path: ./
          export_debug: false           # Ensure release build
          use_preset_export_path: true
          export_preset_name: Web
          create_release: false         # Don't create GitHub release
          archive_export_output: false  # Don't create archive

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build